name: Coverage

on:
  push:
    branches: [ "master" ]
    paths: '**.py'
  workflow_dispatch:

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Gather coverage data
        run: |
          python -m coverage run -m unittest discover
      - name: XML reporting
        run: |
          python -m coverage xml
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
