on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(echo '${{ github.ref }}' | sed -r 's/v//g')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: semanticscholar-${{ steps.version.outputs.version }}
          body: |
            Version ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
